version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: simple
    filename: katia.log
    maxBytes: 102400
    backupCount: 1
loggers:
  KatiaInterpreter:
    level: INFO
    handlers: [console, file]
  KatiaRecognizer:
    level: INFO
    handlers: [console, file]
  KatiaSpeaker:
    level: INFO
    handlers: [console, file]
  KatiaOwner:
    level: INFO
    handlers: [console, file]
  Katia:
    level: INFO
    handlers: [console, file]