name: publish
on: [release]
permissions:
  contents: read

jobs:
  publish:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install poetry
        run: |
          python -m pip install poetry==1.1.11
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install extra requirements for pyaudio
        run: |
          sudo apt-get install libasound-dev
          sudo apt-get install portaudio19-dev
          pip install pyaudio --user
          sudo apt-get install python3-pyaudio
          sudo apt install -y python3.11-dev
      - name: Add token
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publish project
        run: |
          poetry publish --build